name: Build and Release Debian Package

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required dependencies
      run: |
        sudo apt update
        sudo apt install -y dpkg-dev fakeroot

    - name: Prepare .deb package structure
      run: |
        # Debian paket yapısını oluştur
        mkdir -p build/linux-image-writer/DEBIAN
        mkdir -p build/linux-image-writer/usr/share/linux-image-writer
        mkdir -p build/linux-image-writer/usr/bin

        # DEBIAN/control dosyasını oluştur
        echo "Package: linux-image-writer" > build/linux-image-writer/DEBIAN/control
        echo "Version: 1.0" >> build/linux-image-writer/DEBIAN/control
        echo "Section: utils" >> build/linux-image-writer/DEBIAN/control
        echo "Priority: optional" >> build/linux-image-writer/DEBIAN/control
        echo "Architecture: all" >> build/linux-image-writer/DEBIAN/control
        echo "Depends: python3, python3-tk" >> build/linux-image-writer/DEBIAN/control
        echo "Maintainer: Doğukan EREN <dogukaneren@yaani.com>" >> build/linux-image-writer/DEBIAN/control
        echo "Description: A simple ISO writer tool for Linux." >> build/linux-image-writer/DEBIAN/control

        # Python betiğini hedef dizine kopyala
        cp linux-image-writer.py build/linux-image-writer/usr/share/linux-image-writer/

        # Çalıştırılabilir script ekle
        echo '#!/bin/bash' > build/linux-image-writer/usr/bin/linux-image-writer
        echo 'python3 /usr/share/linux-image-writer/linux-image-writer.py' >> build/linux-image-writer/usr/bin/linux-image-writer
        chmod +x build/linux-image-writer/usr/bin/linux-image-writer

    - name: Build .deb package
      run: |
        fakeroot dpkg-deb --build build/linux-image-writer

    - name: Upload Debian package
      uses: actions/upload-artifact@v3
      with:
        name: linux-image-writer
        path: build/linux-image-writer.deb

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: linux-image-writer

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: linux-image-writer.deb
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        name: Linux Image Writer - Latest Release
        body: |
          This release includes the Linux Image Writer tool packaged as a `.deb` file.
        replacesArtifacts: true
        skipIfReleaseExists: false
